services:
  db-test:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddinc-test
    ports:
      - "5433:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data

volumes:
  pgdata-test: