export const LORE_SUBTYPES = [
  { value: 'ideology', label: 'Ideology' },
  { value: 'philosophy', label: 'Philosophy' },
  { value: 'cosmology', label: 'Cosmology' },
  { value: 'religion', label: 'Religion' },
  { value: 'myth', label: 'Myth' },
  { value: 'prophecy', label: 'Prophecy' },
  { value: 'arcane', label: 'Arcane Lore' },
  { value: 'ritual', label: 'Ritual' },
  { value: 'history', label: 'History' },
  { value: 'event', label: 'Event' },
  { value: 'war', label: 'War' },
  { value: 'treaty', label: 'Treaty' },
  { value: 'law_policy', label: 'Law / Policy' },
  { value: 'disaster', label: 'Disaster' },
  { value: 'culture', label: 'Culture' },
  { value: 'tradition', label: 'Tradition' },
  { value: 'language', label: 'Language' },
  { value: 'holiday', label: 'Holiday / Festival' },
  { value: 'landmark', label: 'Landmark' },
  { value: 'geology', label: 'Geology' },
  { value: 'technology', label: 'Technology' },
  { value: 'tome', label: 'Tome / Text' },
  { value: 'legendary_figure', label: 'Legendary Figure' },
  { value: 'general', label: 'General Lore' },
];
